const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      catagory: 'Shirts',
      image: '/images/p1.jpg',
      price: '$' + 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      catagory: 'Shirts',
      image: '/images/p2.jpg',
      price: '$' + 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim pant',
      slug: 'nike-slim-pant',
      catagory: 'Pants',
      image: '/images/p3.jpg',
      price: '$' + 100,
      countInStock: 15,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 14,
      description: 'high quality pant',
    },
    {
      name: 'Adidas Fit pant',
      slug: 'adidas-fit-pant',
      catagory: 'Pants',
      image: '/images/p4.jpg',
      price: '$' + 200,
      countInStock: 5,
      brand: 'Adidas',
      rating: 3,
      numReviews: 12,
      description: 'high quality pant',
    },
  ],
};

export default data;
